name: 'Export PNGs'
description: 'Export PNG files from a Kicad PCB'
inputs:
  pcb_file:
    description: 'Kicad input file'
    required: true
  pngs_dir:
    description: 'PNGs folder'
    required: true
  theme:
    default: '-s set-blue-enig'
  # flags:
  #   description: 'Additional flags for pcbdraw'
  #   default: ''
runs:
  using: 'docker'
  image: 'docker://yaqwsx/kikit:v1.1.0'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      mkdir -p $GITHUB_WORKSPACE/${{ inputs.pngs_dir }} ;
      pcbdraw plot ${{ inputs.theme }} --silent $GITHUB_WORKSPACE/${{ inputs.pcb_file }} $GITHUB_WORKSPACE/${{ inputs.pngs_dir }}/front.png
      pcbdraw plot --side back ${{ inputs.theme }} --silent $GITHUB_WORKSPACE/${{ inputs.pcb_file }} $GITHUB_WORKSPACE/${{ inputs.pngs_dir }}/back.png
