on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.kicad_pcb"

name: Render Previews
jobs:
  pngs:
    runs-on: ubuntu-latest
    name: "Export as PNGs"
    steps:
      # CHECKOUT
      - name: Checkout
        uses: actions/checkout@v2

      # MAKE PREVIEWS
      - name: Swipe Light
        uses: ./.github/actions/export-pngs
        with:
          pcb_file: '"./main.kicad_pcb"'
          pngs_dir: ./gallery/main/

      # UPDATE GALLERY
      - name: Update gallery
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: "Update gallery (automated)"
          commit_user_name: GitHub Actions Bot
          file_pattern: "**/*.png"
